{{- if .Values.webhook.enabled -}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ include "slack-operator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "slack-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - "{{ include "slack-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc"
  - "{{ include "slack-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: {{ include "slack-operator.fullname" . }}-selfsigned-issuer
  secretName:  {{ include "slack-operator.tlsSecretName" . }}
{{- end -}}