{{- if not (.Capabilities.APIVersions.Has "slack.stakater.com/v1alpha1") -}}
    {{- fail "Required CRDs are missing, slack-operator-crds chart is a pre-requisite of this chart" }}
{{ end }}

{{- if .Values.webhook.enabled }}

{{- if not (.Capabilities.APIVersions.Has "cert-manager.io/v1alpha2") -}}
    {{- fail "cert-manager is not installed" }}
{{ end }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ include "slack-operator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "slack-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - "{{ include "slack-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc"
  - "{{ include "slack-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: {{ include "slack-operator.fullname" . }}-selfsigned-issuer
  secretName:  webhook-server-cert
{{- end -}}