{{- if .Values.webhook.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "slack-operator.fullname" . }}-serving-cert
  creationTimestamp: null
  name: {{ include "slack-operator.fullname" . }}-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "slack-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-slack-stakater-com-v1alpha1-channel
  failurePolicy: Fail
  name: mchannel.kb.io
  rules:
  - apiGroups:
    - slack.stakater.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - channels
{{- end -}}
