{{- if not (.Capabilities.APIVersions.Has "slack.stakater.com/v1alpha1") -}}
    {{- fail "Required CRDs are missing, slack-operator-crds chart is a pre-requisite of this chart" }}
{{ end }}

{{- if .Values.rbac.enabled -}}
{{- if .Values.rbac.allowLeaderElectionRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "slack-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "slack-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "slack-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  
{{- end }}
