{{- if not (.Capabilities.APIVersions.Has "slack.stakater.com/v1alpha1") -}}
    {{- fail "Required CRDs are missing, slack-operator-crds chart is a pre-requisite of this chart" }}
{{ end }}

{{- if .Values.webhook.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}r/{{ include "slack-operator.fullname" . }}-serving-cert
  creationTimestamp: null
  name: {{ include "slack-operator.fullname" . }}-validating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ include "slack-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-slack-stakater-com-v1alpha1-channel
    failurePolicy: Fail
    name: vchannel.kb.io
    rules:
    - apiGroups:
      - slack.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - channels
{{- end -}}

